name: Publish Helm Chart to GitHub Pages
on:
  workflow_run:
    workflows: ["Release Helm Charts"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Install chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: main-charts
          publish_branch: gs-pages
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
