name: Publish Helm Chart to GitHub Pages
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Install chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: main-charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
